# To build use: docker build -t xosproject/xos-gui-extension-builder .

FROM node:argon

# Set environment vars
ENV CODE_SOURCE .
ENV CODE_DEST /var/www

RUN mkdir -p ${CODE_DEST}

# Add the app deps
COPY ${CODE_SOURCE}/package.json ${CODE_SOURCE}/typings.json ${CODE_DEST}/

# Install Deps
WORKDIR ${CODE_DEST}
RUN npm install \
 && npm run typings

# Label image
ARG org_label_schema_schema_version=1.0
ARG org_label_schema_name=xos-gui-extension-builder
ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown

LABEL org.label-schema.schema-version=$org_label_schema_schema_version \
      org.label-schema.name=$org_label_schema_name \
      org.label-schema.version=$org_label_schema_version \
      org.label-schema.vcs-url=$org_label_schema_vcs_url \
      org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
      org.label-schema.build-date=$org_label_schema_build_date \
      org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date

